[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build.environment]
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"

[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "next dev -H 0.0.0.0"
  
[context.dev.environment]
SUPABASE_URL = "https://cgjpizkbyynicmknztdb.supabase.co"
SUPABASE_KEY = "sb_secret_m1vpNuZZcQkvAlA9tNit6g_CQzJ996i"
NPM_CONFIG_BUILD_FROM_SOURCE = "true"